name: Build Pull Request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: tyler-technologies-oss/forge-automation-shared/.github/workflows/wf-build-and-test.yml@v2.9.0
    secrets:
      NPM_TOKEN: ${{ secrets.FORGE_NPM_TOKEN }}
